version: '3.7'

services:

  ui:
    image: mcbcmusic-ui
    build: ui
    profiles: ["dev"]
    volumes:
      - ./ui/src:/app/src
      - ./ui/public:/app/public
      - ./ui/node_modules:/app/node_modules
    ports:
      - 8080:8080

  web:
    image: mcbcmusic-web
    build: nginx
    profiles: ["prod"]
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./uidist:/usr/share/nginx/html
    ports:
      - 80:80
    networks:
      - mynet

  api-prod:
    image: mcbcmusic-api-prod
    build: api
    profiles: ["prod"]
    environment: 
      - FLASK_SERVER_PORT=9091
      - PCO_APP_ID=$PCO_APP_ID
      - PCO_SECRET=$PCO_SECRET
      - PCO_WEBAPP_LOGIN_USERNAME=$PCO_WEBAPP_LOGIN_USERNAME
      - PCO_WEBAPP_LOGIN_PASSWORD=$PCO_WEBAPP_LOGIN_PASSWORD
      - FLASK_SECRET_KEY=$FLASK_SECRET_KEY
      - SENDGRID_API_KEY=$SENDGRID_API_KEY
      - DB_PATH=/db/mcbcmusic.sqlite3
    volumes:
      - ./api:/src 
      - ./db:/db
    networks:
      - mynet

  # The following starts only when the profile is set to dev
  api-dev:
    image: mcbcmusic-api-dev
    build: api
    profiles: ["dev"]
    environment: 
      - FLASK_SERVER_PORT=9091
      - PCO_APP_ID=$PCO_APP_ID
      - PCO_SECRET=$PCO_SECRET
      - PCO_WEBAPP_LOGIN_USERNAME=$PCO_WEBAPP_LOGIN_USERNAME
      - PCO_WEBAPP_LOGIN_PASSWORD=$PCO_WEBAPP_LOGIN_PASSWORD
    volumes:
      - ./api:/src
    ports:
      - 9091:9091
    networks:
      - mynet


networks:
    mynet: